ldap:
  server_uri: ldaps://MN-AD-01.amanomcgann.com
  user_dn: CN=svc_onboarding Offboarding,CN=Users,DC=amanomcgann,DC=com
  password: <password>
  base_dn: DC=amanomcgann,DC=com
  user_ou: CN=Users,DC=amanomcgann,DC=com
  use_ssl: true
  manager_search_filter: (&(objectClass=user)(|(title=Manager)(title=Director)))
  manager_attributes:
  - displayName
  - mail
  - title
  group_search_base: OU=User Groups,DC=amanomcgann,DC=com
sync:
  command: powershell.exe -NoProfile -NonInteractive -Command "Import-Module ADSync;
    Start-ADSyncSyncCycle -PolicyType Delta"
  shell: false
  timeout: 180
storage:
  job_roles_file: data\job_roles.yaml
  license_jobs_file: data\license_jobs.json
m365:
  tenant_id: 7c98eced-e44f-40c3-b38b-242eeaebde35
  client_id: 33a87ac0-5965-4a22-9f5b-e45dd48d5211
  client_secret: <client_secret>
  sku_cache_file: data\m365_skus.json
  cache_ttl_minutes: 720
  default_usage_location: US
auth:
  enabled: false
  tenant_id: 7c98eced-e44f-40c3-b38b-242eeaebde35
  client_id: 33a87ac0-5965-4a22-9f5b-e45dd48d5211
  client_secret: <client_secret>
  redirect_uri: http://locahost:5000/auth/callback
  allowed_groups:
  - 09ba685a-0c4c-4921-b8f1-51afa9a30442
  scopes:
  - https://graph.microsoft.com/User.Read
  - https://graph.microsoft.com/GroupMember.Read.All
