ldap:
  server_uri: ldaps://MN-AD-01.amanomcgann.com
  user_dn: CN=svc_onboarding Offboarding,CN=Users,DC=amanomcgann,DC=com
  password: '%3#nqNIdDpvn'
  base_dn: DC=amanomcgann,DC=com
  user_ou: CN=Users,DC=amanomcgann,DC=com
  use_ssl: true
  manager_search_filter: (&(objectClass=user)(|(title=Manager)(title=Director)))
  manager_attributes:
  - displayName
  - mail
  - title
sync:
  command: powershell.exe -NoProfile -NonInteractive -Command "Invoke-Command -ComputerName
    'mn-adsync-03' -ScriptBlock { Import-Module ADSync; Start-ADSyncSyncCycle -PolicyType
    Delta }"
  shell: false
  timeout: 180
storage:
  job_roles_file: data\job_roles.yaml
