ldap:
  server_uri: mock://demo
  user_dn: CN=ServiceAccount,CN=Users,DC=example,DC=com
  password: ChangeMe123!
  base_dn: DC=example,DC=com
  user_ou: OU=Employees,DC=example,DC=com
  use_ssl: true
  manager_search_filter: (&(objectClass=user)(|(title=Manager)(title=Director)))
  manager_attributes:
  - displayName
  - mail
  - title
  group_search_base: OU=Groups,DC=example,DC=com
sync:
  command: echo "Mock sync completed"
  shell: true
  timeout: 60
storage:
  job_roles_file: data/job_roles.yaml
  license_jobs_file: data/license_jobs.json
m365:
  tenant_id: 00000000-0000-0000-0000-000000000000
  client_id: 00000000-0000-0000-0000-000000000000
  client_secret: your_client_secret_here
  sku_cache_file: data/m365_skus.json
  cache_ttl_minutes: 720
  default_usage_location: US
  cert_thumbprint: 0000000000000000000000000000000000000000
  exo_organization: example.com
auth:
  enabled: false
  tenant_id: 00000000-0000-0000-0000-000000000000
  client_id: 00000000-0000-0000-0000-000000000000
  client_secret: your_auth_client_secret_here
  redirect_uri: http://localhost:5000/auth/callback
  allowed_groups:
  - 00000000-0000-0000-0000-000000000000
  scopes:
  - https://graph.microsoft.com/User.Read
  - https://graph.microsoft.com/GroupMember.Read.All
